---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: master-noop-rules
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
    storage:
      files:
      - contents:
          source: data:,%20
        mode: 384
        path: /root/noop
